"""add bio birthday name_color to users

Revision ID: 5286ff7a97a4
Revises: f6216a9640a9
Create Date: 2026-06-17 10:16:17.434513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5286ff7a97a4'
down_revision: Union[str, Sequence[str], None] = 'f6216a9640a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=70), nullable=True))
    op.add_column('users', sa.Column('birthday', sa.String(), nullable=True))
    op.add_column('users', sa.Column('name_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name_color')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
